// <auto-generated>
/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SpoolMan.Api.Client;

namespace SpoolMan.Api.Model
{
    /// <summary>
    /// Defines SpoolType
    /// </summary>
    public enum SpoolType
    {
        /// <summary>
        /// Enum Plastic for value: plastic
        /// </summary>
        Plastic = 1,

        /// <summary>
        /// Enum Cardboard for value: cardboard
        /// </summary>
        Cardboard = 2,

        /// <summary>
        /// Enum Metal for value: metal
        /// </summary>
        Metal = 3
    }

    /// <summary>
    /// Converts <see cref="SpoolType"/> to and from the JSON value
    /// </summary>
    public static class SpoolTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SpoolType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SpoolType FromString(string value)
        {
            if (value.Equals("plastic"))
                return SpoolType.Plastic;

            if (value.Equals("cardboard"))
                return SpoolType.Cardboard;

            if (value.Equals("metal"))
                return SpoolType.Metal;

            throw new NotImplementedException($"Could not convert value to type SpoolType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SpoolType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SpoolType? FromStringOrDefault(string value)
        {
            if (value.Equals("plastic"))
                return SpoolType.Plastic;

            if (value.Equals("cardboard"))
                return SpoolType.Cardboard;

            if (value.Equals("metal"))
                return SpoolType.Metal;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SpoolType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SpoolType value)
        {
            if (value == SpoolType.Plastic)
                return "plastic";

            if (value == SpoolType.Cardboard)
                return "cardboard";

            if (value == SpoolType.Metal)
                return "metal";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SpoolType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SpoolTypeJsonConverter : JsonConverter<SpoolType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SpoolType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SpoolType? result = rawValue == null
                ? null
                : SpoolTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SpoolType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="spoolType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SpoolType spoolType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(spoolType.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SpoolType"/>
    /// </summary>
    public class SpoolTypeNullableJsonConverter : JsonConverter<SpoolType?>
    {
        /// <summary>
        /// Returns a SpoolType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SpoolType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SpoolType? result = rawValue == null
                ? null
                : SpoolTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="spoolType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SpoolType? spoolType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(spoolType?.ToString() ?? "null");
        }
    }
}
