/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using SpoolMan.Api.Api;
using SpoolMan.Api.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace SpoolMan.Api.Test.Api
{
    /// <summary>
    ///  Class for testing OtherApi
    /// </summary>
    public sealed class OtherApiTests : ApiTestsBase
    {
        private readonly IOtherApi _instance;

        public OtherApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IOtherApi>();
        }

        /// <summary>
        /// Test FindArticleNumbersArticleNumberGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FindArticleNumbersArticleNumberGetAsyncTest()
        {
            var response = await _instance.FindArticleNumbersArticleNumberGetAsync();
            var model = response.Ok();
            Assert.IsType<List<string>>(model);
        }

        /// <summary>
        /// Test FindLocationsLocationGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FindLocationsLocationGetAsyncTest()
        {
            var response = await _instance.FindLocationsLocationGetAsync();
            var model = response.Ok();
            Assert.IsType<List<string>>(model);
        }

        /// <summary>
        /// Test FindLotNumbersLotNumberGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FindLotNumbersLotNumberGetAsyncTest()
        {
            var response = await _instance.FindLotNumbersLotNumberGetAsync();
            var model = response.Ok();
            Assert.IsType<List<string>>(model);
        }

        /// <summary>
        /// Test FindMaterialsMaterialGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FindMaterialsMaterialGetAsyncTest()
        {
            var response = await _instance.FindMaterialsMaterialGetAsync();
            var model = response.Ok();
            Assert.IsType<List<string>>(model);
        }

        /// <summary>
        /// Test RenameLocationLocationLocationPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RenameLocationLocationLocationPatchAsyncTest()
        {
            string location = default!;
            RenameLocationBody renameLocationBody = default!;
            var response = await _instance.RenameLocationLocationLocationPatchAsync(location, renameLocationBody);
            var model = response.Ok();
            Assert.IsType<string>(model);
        }
    }
}
