/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using SpoolMan.Api.Api;
using SpoolMan.Api.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace SpoolMan.Api.Test.Api
{
    /// <summary>
    ///  Class for testing VendorApi
    /// </summary>
    public sealed class VendorApiTests : ApiTestsBase
    {
        private readonly IVendorApi _instance;

        public VendorApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IVendorApi>();
        }

        /// <summary>
        /// Test AddVendorVendorPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AddVendorVendorPostAsyncTest()
        {
            VendorParameters vendorParameters = default!;
            var response = await _instance.AddVendorVendorPostAsync(vendorParameters);
            var model = response.Ok();
            Assert.IsType<Vendor>(model);
        }

        /// <summary>
        /// Test DeleteVendorVendorVendorIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteVendorVendorVendorIdDeleteAsyncTest()
        {
            int vendorId = default!;
            var response = await _instance.DeleteVendorVendorVendorIdDeleteAsync(vendorId);
            var model = response.Ok();
            Assert.IsType<Message>(model);
        }

        /// <summary>
        /// Test FindVendorVendorGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FindVendorVendorGetAsyncTest()
        {
            Client.Option<string?> name = default!;
            Client.Option<string?> externalId = default!;
            Client.Option<string?> sort = default!;
            Client.Option<int?> limit = default!;
            Client.Option<int> offset = default!;
            var response = await _instance.FindVendorVendorGetAsync(name, externalId, sort, limit, offset);
            var model = response.Ok();
            Assert.IsType<List<Vendor>>(model);
        }

        /// <summary>
        /// Test GetVendorVendorVendorIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetVendorVendorVendorIdGetAsyncTest()
        {
            int vendorId = default!;
            var response = await _instance.GetVendorVendorVendorIdGetAsync(vendorId);
            var model = response.Ok();
            Assert.IsType<Vendor>(model);
        }

        /// <summary>
        /// Test UpdateVendorVendorVendorIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateVendorVendorVendorIdPatchAsyncTest()
        {
            int vendorId = default!;
            VendorUpdateParameters vendorUpdateParameters = default!;
            var response = await _instance.UpdateVendorVendorVendorIdPatchAsync(vendorId, vendorUpdateParameters);
            var model = response.Ok();
            Assert.IsType<Vendor>(model);
        }
    }
}
