/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpoolMan.Api.Model;
using SpoolMan.Api.Client;
using System.Reflection;

namespace SpoolMan.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalMaterial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalMaterialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalMaterial
        //private ExternalMaterial instance;

        public ExternalMaterialTests()
        {
            // TODO uncomment below to create an instance of ExternalMaterial
            //instance = new ExternalMaterial();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalMaterial
        /// </summary>
        [Fact]
        public void ExternalMaterialInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalMaterial
            //Assert.IsType<ExternalMaterial>(instance);
        }

        /// <summary>
        /// Test the property 'Material'
        /// </summary>
        [Fact]
        public void MaterialTest()
        {
            // TODO unit test for the property 'Material'
        }

        /// <summary>
        /// Test the property 'Density'
        /// </summary>
        [Fact]
        public void DensityTest()
        {
            // TODO unit test for the property 'Density'
        }

        /// <summary>
        /// Test the property 'ExtruderTemp'
        /// </summary>
        [Fact]
        public void ExtruderTempTest()
        {
            // TODO unit test for the property 'ExtruderTemp'
        }

        /// <summary>
        /// Test the property 'BedTemp'
        /// </summary>
        [Fact]
        public void BedTempTest()
        {
            // TODO unit test for the property 'BedTemp'
        }
    }
}
