/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpoolMan.Api.Model;
using SpoolMan.Api.Client;
using System.Reflection;

namespace SpoolMan.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalFilament
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalFilamentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalFilament
        //private ExternalFilament instance;

        public ExternalFilamentTests()
        {
            // TODO uncomment below to create an instance of ExternalFilament
            //instance = new ExternalFilament();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalFilament
        /// </summary>
        [Fact]
        public void ExternalFilamentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalFilament
            //Assert.IsType<ExternalFilament>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Fact]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Material'
        /// </summary>
        [Fact]
        public void MaterialTest()
        {
            // TODO unit test for the property 'Material'
        }

        /// <summary>
        /// Test the property 'Density'
        /// </summary>
        [Fact]
        public void DensityTest()
        {
            // TODO unit test for the property 'Density'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'Diameter'
        /// </summary>
        [Fact]
        public void DiameterTest()
        {
            // TODO unit test for the property 'Diameter'
        }

        /// <summary>
        /// Test the property 'SpoolWeight'
        /// </summary>
        [Fact]
        public void SpoolWeightTest()
        {
            // TODO unit test for the property 'SpoolWeight'
        }

        /// <summary>
        /// Test the property 'SpoolType'
        /// </summary>
        [Fact]
        public void SpoolTypeTest()
        {
            // TODO unit test for the property 'SpoolType'
        }

        /// <summary>
        /// Test the property 'ColorHex'
        /// </summary>
        [Fact]
        public void ColorHexTest()
        {
            // TODO unit test for the property 'ColorHex'
        }

        /// <summary>
        /// Test the property 'ColorHexes'
        /// </summary>
        [Fact]
        public void ColorHexesTest()
        {
            // TODO unit test for the property 'ColorHexes'
        }

        /// <summary>
        /// Test the property 'ExtruderTemp'
        /// </summary>
        [Fact]
        public void ExtruderTempTest()
        {
            // TODO unit test for the property 'ExtruderTemp'
        }

        /// <summary>
        /// Test the property 'BedTemp'
        /// </summary>
        [Fact]
        public void BedTempTest()
        {
            // TODO unit test for the property 'BedTemp'
        }

        /// <summary>
        /// Test the property 'Finish'
        /// </summary>
        [Fact]
        public void FinishTest()
        {
            // TODO unit test for the property 'Finish'
        }

        /// <summary>
        /// Test the property 'MultiColorDirection'
        /// </summary>
        [Fact]
        public void MultiColorDirectionTest()
        {
            // TODO unit test for the property 'MultiColorDirection'
        }

        /// <summary>
        /// Test the property 'Pattern'
        /// </summary>
        [Fact]
        public void PatternTest()
        {
            // TODO unit test for the property 'Pattern'
        }

        /// <summary>
        /// Test the property 'Translucent'
        /// </summary>
        [Fact]
        public void TranslucentTest()
        {
            // TODO unit test for the property 'Translucent'
        }

        /// <summary>
        /// Test the property 'Glow'
        /// </summary>
        [Fact]
        public void GlowTest()
        {
            // TODO unit test for the property 'Glow'
        }
    }
}
