/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpoolMan.Api.Model;
using SpoolMan.Api.Client;
using System.Reflection;

namespace SpoolMan.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Info
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Info
        //private Info instance;

        public InfoTests()
        {
            // TODO uncomment below to create an instance of Info
            //instance = new Info();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Info
        /// </summary>
        [Fact]
        public void InfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" Info
            //Assert.IsType<Info>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'DebugMode'
        /// </summary>
        [Fact]
        public void DebugModeTest()
        {
            // TODO unit test for the property 'DebugMode'
        }

        /// <summary>
        /// Test the property 'AutomaticBackups'
        /// </summary>
        [Fact]
        public void AutomaticBackupsTest()
        {
            // TODO unit test for the property 'AutomaticBackups'
        }

        /// <summary>
        /// Test the property 'DataDir'
        /// </summary>
        [Fact]
        public void DataDirTest()
        {
            // TODO unit test for the property 'DataDir'
        }

        /// <summary>
        /// Test the property 'LogsDir'
        /// </summary>
        [Fact]
        public void LogsDirTest()
        {
            // TODO unit test for the property 'LogsDir'
        }

        /// <summary>
        /// Test the property 'BackupsDir'
        /// </summary>
        [Fact]
        public void BackupsDirTest()
        {
            // TODO unit test for the property 'BackupsDir'
        }

        /// <summary>
        /// Test the property 'DbType'
        /// </summary>
        [Fact]
        public void DbTypeTest()
        {
            // TODO unit test for the property 'DbType'
        }

        /// <summary>
        /// Test the property 'GitCommit'
        /// </summary>
        [Fact]
        public void GitCommitTest()
        {
            // TODO unit test for the property 'GitCommit'
        }

        /// <summary>
        /// Test the property 'BuildDate'
        /// </summary>
        [Fact]
        public void BuildDateTest()
        {
            // TODO unit test for the property 'BuildDate'
        }
    }
}
