/*
 * Spoolman REST API v1
 *
 *      REST API for Spoolman.      The API is served on the path `/api/v1/`.      Some endpoints also serve a websocket on the same path. The websocket is used to listen for changes to the data     that the endpoint serves. The websocket messages are JSON objects. Additionally, there is a root-level websocket     endpoint that listens for changes to any data in the database.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SpoolMan.Api.Model;
using SpoolMan.Api.Client;
using System.Reflection;

namespace SpoolMan.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SpoolType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpoolTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpoolType
        //private SpoolType instance;

        public SpoolTypeTests()
        {
            // TODO uncomment below to create an instance of SpoolType
            //instance = new SpoolType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpoolType
        /// </summary>
        [Fact]
        public void SpoolTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpoolType
            //Assert.IsType<SpoolType>(instance);
        }
    }
}
