---
name: Build iOS App

'on':
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install --project-directory=BambuManIOS || true

      - name: Set up signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_DIST_CERT }}
          p12-password: ${{ secrets.IOS_DIST_CERT_PASSWORD }}

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISION_PROFILE }}" > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build IPA
        run: |
          xcodebuild \
            -project BambuManIOS.xcodeproj \
            -scheme BambuManIOS \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/BambuManIOS.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM


      - name: Export archive
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/BambuManIOS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build/ipa \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM


      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: BambuManIOS
          path: build/ipa/*.ipa
